### ISSUE TITLE
В разделе Цвет значков и тон Emoji в графе Starstruck отображается иконка Quickdraw

### ISSUE THREAD

**Issue by ovdro** [gomzyakov/github-achievements#19]
![image](https://user-images.githubusercontent.com/90638536/200509613-533ba649-df1c-48cf-b44e-90b656b299a5.png)

**Comment by gomzyakov** [comment]
@ovdro 

Ещё раз спасибо за внимательность!) Исправил в https://github.com/gomzyakov/github-achievements/pull/21
